<a href="https://colab.research.google.com/github/KhalilPendari/DSML-Git2/blob/main/python%20Interview%20questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [6]:
arr1=np.arange(0,2)
arr2=np.arange(6,10).reshape(2,-2)
arr3=np.array([[0,1],
               [1,0]])

arr1,arr2,arr3

(array([0, 1]),
 array([[6, 7],
        [8, 9]]),
 array([[0, 1],
        [1, 0]]))

Question -1
   Can you add arr1 and arr2? if so, explain the technique

In [7]:
arr1+arr2

array([[ 6,  8],
       [ 8, 10]])

Explanation :
numpy uses broadcasting technique here. it is a speacial future numpy that allows the numpy to perform specific operations on arrays of different shapes without explicitely copying the data.

Question 2 :
    How do you concatenate arr2 and arr3 ( Horizontally and Vertically ).

In [14]:
np.vstack((arr2,arr3))

array([[6, 7],
       [8, 9],
       [0, 1],
       [1, 0]])

In [13]:
np.hstack((arr2,arr3))

array([[6, 7, 0, 1],
       [8, 9, 1, 0]])

Explanation :
  Here I used vstack for concatenate arrays vertically. and Hstack for concatenating Horizontally.

  we have a np.concate() fucntion as well to concatenate both ways vertically and horizontally. but we need to specify axis there.

Question 3 :
   Find the index of the top 2 elements of [4,1,5,7,0]

In [16]:
np.argmax([4,1,5,7,0])

np.int64(3)

In [17]:
np.argsort([4,1,5,7,0])

array([4, 1, 0, 2, 3])

explanation :
 I used the argsort() to get their index position based on sorting .

**question:**

 Create a vector with values ranging from 10 to 49 (inclusive)

In [55]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Question :**

  Find the indices of non-zero elements from [1,2,0,0,4,0]

In [64]:
num=np.array([1,2,0,0,4,0])
idx=np.where(num!=0)[0]
print(idx)

[0 1 4]


Question :
   Add a border filled with zeros  around  an existing array

In [66]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
ones[0,]=0
ones[1,[0,2]]=0
ones[2]=0

In [72]:
ones

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

**Pandas**

In [46]:
data={'Name': ['John','Emma','Luke','Emily','Oliver'],
      'Age':[25,28,32,21,35],
      'Gender':['Male','Female','Male','Female','Male'],
      'Salary':[50000,60000,70000,55000,80000]}

df=pd.DataFrame(data)
df

Name  Age  Gender  Salary
0    John   25    Male   50000
1    Emma   28  Female   60000
2    Luke   32    Male   70000
3   Emily   21  Female   55000
4  Oliver   35    Male   80000

In [21]:
df.shape

(5, 4)

Question 1:
   select the rows where age is between 25 and 30 (both inclusive)

In [24]:
(df['Age']>=25 )&(df['Age']<=30)

0     True
1     True
2    False
3    False
4    False
Name: Age, dtype: bool

In [25]:
df[(df['Age']>=25 )&(df['Age']<=30)]

Name  Age  Gender  Salary
0  John   25    Male   50000
1  Emma   28  Female   60000

Question 2 :
    Find the maximum and median salary of each Gender

In [37]:
df.groupby(['Gender']).aggregate(salary_max=('Salary','max'),salary_median=('Salary','median'))

salary_max  salary_median
Gender                           
Female       60000        57500.0
Male         80000        70000.0

**or**

In [38]:
df.groupby(['Gender'])['Salary'].agg(['max','median'])

max   median
Gender                
Female  60000  57500.0
Male    80000  70000.0

question 3 :
    Apply a custom function to each member, calculating bonus on their Age and Salary



The bonus should be 10% of the salary  for
individuals below the age of 30 and 15% for individuals  above or equal to the age 30

In [49]:
def bonus (x):
  if x['Age']<30:
    x['Bonus']=x['Salary']*10/100
    return x

  if x['Age']>=30:
    x['Bonus']=x['Salary']*15/100
    return x


In [52]:
df=df.apply(bonus,axis=1)
df

Name  Age  Gender  Salary    Bonus
0    John   25    Male   50000   5000.0
1    Emma   28  Female   60000   6000.0
2    Luke   32    Male   70000  10500.0
3   Emily   21  Female   55000   5500.0
4  Oliver   35    Male   80000  12000.0

In [51]:
df

Name  Age  Gender  Salary    Bonus
0    John   25    Male   50000   5000.0
1    Emma   28  Female   60000   6000.0
2    Luke   32    Male   70000  10500.0
3   Emily   21  Female   55000   5500.0
4  Oliver   35    Male   80000  12000.0